package com.pigdogbay.roboquipper;

import java.util.Random;

public final class Quotes
{
	static String _Quotes[] = {
			"COMMAND.COM\nLOAD BIOS\nMEMORY SET\nSYSTEM STATUS\nOK\n",
			"Well give the man a hand!",
			"Can you fly, Bobby?",
			"I'd buy that for a dollar",
			"You know, he's a\n sweet old man.",
			"Pretty simple math,\n huh, Bob?",
			"You better pray\n that unholy monster of yours\n doesn't screw up. ",
			"They'll fix you.\n They fix everything.\n",
			"Looking for me?",
			"I know you! \nYou're dead! \nWe killed you!",
			"You better watch your back,\n Bob.",
			"Jones is gonna come looking\n for you.",
			"Too bad about Kinney, huh?",
			"He fumbled the ball,\n I was there to pick it up.",
			"Soon as some \npoor schmuck volunteers.",
			"Excuse me, I have to go. \nSomewhere there is \na crime happening.",
			"Let me make something\n clear to you. \nHe doesn't have a name. \nHe has a program. \nHe's product.",
			"Bitches, leave!",
			"See, I got this problem. \nCops don't like me. \nSo I don't like cops.",
			"Okay Miller! \nDon't hurt the mayor! \nWe'll give you what you want!",
			"Nobody ever takes me seriously! \nWe'll get serious now... \nand kiss the mayor's ass goodbye!",
			"Nice shooting, son. \nWhat's your name?",
			"Forget it, kid. \nThis guy's a serious assh*@e.",
			"Your client's a scumbag, \nyou're a scumbag, \nand scumbags see the judge \non Monday morning.",
			"Now get out of my office, \nand take laughing boy with you!",
			"Murphy, it's you!",
			"Please put down your weapon. \nYou have 20 seconds to comply.",
			"Four... three... two... one... \nI am now authorized to use physical force!",
			"Thank you for your cooperation. \nGood night.",
			"Book him! \nWhat's the charge? \nHe's a cop killer.",
			"Dick, you're *fired*!",
			"She was sweeeeet, mmph-mmm-mmm. \nI took her out, Ha-ha-ha-ha-ha-ha...",
			"You probably don't think \nI'm a very nice guy... do ya? ",
			"I had a guaranteed military sale with ED209! \nRenovation program! \nSpare parts for 25 years! \nWho cares if it worked or not!",
			"First, don't mess with me. \nI'm a desperate man! \nAnd second, I want some fresh coffee. \nAnd third, I want a recount! \nAnd no matter how it turns out, \nI want my old job back!",
			"I'm cashing you out, Bob.",
			"Oooh. Guns, guns, guns. C'mon, Sal. \nThe Tigers are playing...",
			"Frankie, blow this ****sucker's head off.",
			"You call this a GLITCH?",
			"I work for Dick Jones! Dick Jones! \nHe's the Number Two Guy at OCP. OCP runs the cops.",
			"Don't mess with Jones, man. \nHe'll make sushi out of you.",
			"Good night, sweet prince.",
			"Nukem. \nGet them before they get you. \nAnother quality home game from Butler Brothers.",
			"Old Detroit has a cancer. \nThat cancer is crime.",
			"What? \nI thought we agreed on total body prosthesis \n now lose the arm okay!",
			"Shut him down, \nprep him for surgery.",
			"Hey, he's old, we're young, and that's life.",
			"Hey, dickey boy, how's tricks? ",
			"That's two million workers living in trailers \n That means drugs, gambling, prostitution...",
			"We practically are the military.",
			"Here at Security Concepts, \nwe're predicting the end of crime in Old Detroit \nwithin 40 days. \nThere's a new guy in town. \nHis name is RoboCop.",
			"Does it hurt? Does it hurt?",
			"Are you a college boy?",
			"The Star Wars Space Peace Platform",
			"That's life in the big city",
			"Hey there buddy boy",
			"Good business is where you find it",
			"Oh Dick, I'm very disappointed",
			"Stay out of trouble",
			"Your move creep",
			"Dead or alive, you're coming with me",
			"And remember, we care",
			"Madame, you have suffered an emotional shock. \nI will notify a rape crisis center.",
			"You mind if I, zip this up?",
			"You gonna be a bad mother******!",
			"I used to call the old man funny names. \nIron Butt. Boner. \nOnce I even called him...***hole.",
			"I always knew where the line was drawn. \nAnd you just stepped over it, \nbuddy-boy.",
			"You've insulted me. \nAnd you've insulted this company \nwith that b*****d creation of yours.",
			"The old man thought it was \npretty important, Dick.",
			"I had to kill Bob Morton \nbecause he made a mistake. \nNow it's time to erase that mistake.",
			"I'm not arresting you anymore.",
			"Robo, any special message \nfor all the kids watching at home?",
			"Something with reclining leather seats, \nthat goes really fast, \nand gets really s****y gas mileage! Alright.",
			"Lieutenant, don't jerk me off! \nWhen people jerk me off, \nI kill them! You wanna see?",
			"SERVE THE PUBLIC TRUST\nPROTECT THE INNOCENT\nUPHOLD THE LAW",
			"It's back! \nBig is back, \nbecause bigger is better than ever! \n6000 SUX: An American Tradition!",
			"I think you better do as he says, \nMr. Kinney.",
			"Are you a good cop, hotshot? \nWhy, sure you are! \nyou gotta be some kind of GREAT cop, \ncoming in here all by yourself. \nWhere's your partner?",
			"Buddy, I think you're slime ",
			"Hey Emil! \nHow's the Gray Bar Motel? \nThey let me keep the shirt. \nNobody popped my cherry!",
			"Cobra Assault Cannon, \nstate of the art, bang bang! ",
			"Make it aggravated assault \nand I can make bail in cash, now.",
			"I can feel them... \nbut I can't remember them.",
			"You're our product. \nAnd we can't very well have our products \nturning against us, can we?",
			"Your ass is mine!",
			"Just give me my ****ing phone call. ",
			"Hello, buddy boy. \nDick Jones here.",
			"I guess you're on your knees right about now. \nBegging for your life. \nPathetic.",
			"You don't feel so cocky now\n do ya Bob?",
			"You know what the tragedy here is, Bob? \nWe could have been friends.",
			"But life goes on, \nit's an old story, \nthe fight for love and glory, \nhuh Bob?",
			"Just kidding.",
			"Somebody wanna call a goddamn paramedic?",
			"Yeah, you better be careful. \nI hear Jones is a real shark.",
			"Pakistan is threatening my border! \nThat's it, buster! No more military aid.",
			"Tastes like baby food!",
			"Doesn't matter, \nwe're gonna blank his memory anyway.",
			"Think about it, chum. \nGood business is where you find it.",
			"Jesus, you really screwed up.",
			"Maybe what we need here \nis a fresh perspective. ",
			"My friends. \nI've had this dream \nfor more than a decade now.",
			"I had to blow the door! \nWhat do you want?",
			"Terrorism is a very tricky business. \nMassive and immediate retaliatioin \nis the best policy.",
			"Okay, fun's over.",
			"Now move! Open the safe pops. \nOpen the god damn safe!",
			"There's a new guy in town. \nHis name is RoboCop.",
			};

	public static String getQuote(int index){
		return _Quotes[index];
	}
	public static String GetRandomQuote()
	{
		int index = _Quotes.length;
		Random rand = new Random();
		index = rand.nextInt(index);
		return _Quotes[index];
	}

}
